module.exports = {
  apps: [
    {
      name: "nexo-backend",
      interpreter: "node",
      script: "src/index.ts",
      node_args: "--import tsx",
      cwd: "D:\\AackREF\\NEXOSITE\\backend",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 50,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "nexo-tunnel",
      script: "C:\\Program Files (x86)\\cloudflared\\cloudflared.exe",
      args: "tunnel run nexo-backend",
      autorestart: true,
      watch: false,
      restart_delay: 5000,
      max_restarts: 100,
      error_file: "./logs/tunnel-error.log",
      out_file: "./logs/tunnel-out.log",
      merge_logs: true,
      time: true,
    },
  ],
};
